cotracker_model_path: ./checkpoints/cotracker_stride_4_wind_8.pth
edit_video_path: ./output.mp4 # change to your own output path
mask_path: null
original_video_path: ./original.mp4 # change to your own original video path
output_path: ./results # change to your own output path
use_mask: false
